test:
  adapter: postgresql
  database: blue_lily_test
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: blue_lily_dev
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql